version: "3.3"
services:
  blogweb_postgresql:
    image: postgres:13
    container_name: blogweb_postgresql
    volumes:
      - blogweb_postgresql:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - blogweb_network
volumes:
  blogweb_postgresql:
    external: true
networks:
  blogweb_network:
    external: true